CREATE TABLE ##temp(	
 [Partner Name] [varchar](200) NULL,
 ['+@q_prev_year + ' MGO ROI] [decimal](16, 1) NULL,
 [Membership Type] [varchar](100) NULL,
 [Business Unit] [varchar](100) NULL,
 ['+@q_prev_year + ' Weighted Sellout ($)] [decimal](16, 1) NULL, 

 ['+@q_prev_year + ' Sellout to Silver & Below] [decimal](16, 1) NULL,
 ['+@q_prev_year + ' Sellout to Gold & Platinum] [decimal](16, 1) NULL,
 ['+@q_prev_year + ' Unweighted Sellout] [decimal](16, 1) NULL,


 [YoY(' + @q_prev_year + ' vs ' + @q_prev_toPevyear_sec_half + ')] [decimal](16, 1) NULL, 
 [Extrapolated ' + @q_year + ' Sellout] [decimal](16, 1) NULL,
 [HoH( ' + @q_year + ' vs ' + @q_prev_year + ')] [decimal](16, 1) NULL, 
 ['+@q_current_year + ' M-POWR Projected Sellout] [decimal](16, 1) NULL,
 [Source of ' + @q_current_year + ' Projected Sellout] [varchar](100) NULL,  
 [YoY( ' +@q_current_year   + ' Projected vs ' + @q_prev_year  + ')] [decimal](16, 1) NULL, 
 [M-POWR ' + @q_current_year + ' Calculated MDF (Round 1)] [decimal](16, 1) NULL,
 [M-POWR ' + @q_current_year + ' Calculated MDF (Round 2)] [decimal](16, 1) NULL,
 [Allocated ' + @q_prev_year + ' Proposed Budget]  [decimal](16, 1) NULL,
 ['+@q_prev_year + ' approved MDF] [decimal](16, 1) NULL,
 ['+@q_current_year + ' allocated MSA] [decimal](16, 1) NULL  DEFAULT ((0)),
 [ARUBA MSA] [decimal](16, 1) NULL  DEFAULT ((0)),
 [Allocated ' + @q_year + ' Proposed Budget]  [decimal](16, 1) NULL,
 ['+@q_year + ' approved MDF] [decimal](16, 1) NULL,
 [Allocated ' + @q_current_year + ' Proposed Budget (Round 1)] [decimal](16, 1) NULL  DEFAULT ((0)),
 [Total ' + @q_current_year + ' Proposed Budget (Round 1)] [decimal](16, 1) NULL,
 [Allocated ' + @q_current_year + ' CarveOut] [decimal](16, 1) NULL  DEFAULT ((0)),
 [Allocated ' + @q_current_year + ' Proposed Budget (Round 2)] [decimal](16, 1) NULL  DEFAULT ((0)),
 ['+@q_current_year + ' vs ' + @q_prev_year + ' MDF Delta] [decimal](16, 1) NULL, 
 [YoY(' +  @q_prev_year + ' vs ' + @q_current_year + ')] [decimal](16, 1) NULL,
 [HoH(' + @q_current_year + ' vs ' + @q_year + ')] [decimal](16, 1) NULL, 
 ['+@q_prev_year + ' MDF/' + @q_prev_year + ' Sellout] [decimal](16, 1) NULL,
 ['+@q_year + ' MDF/' + @q_year + ' Sellout] [decimal](16, 1) NULL,
 ['+@q_current_year + ' MDF/' + @q_current_year + ' Projected Sellout] [decimal](16, 1) NULL,
 ['+@q_prev_toPevyear_sec_half + ' to ' + @q_prev_year + ' Median Avg MDF/Sellout] [decimal](16, 1) NULL,
 ['+@q_prev_year + ' and ' + @q_current_year + ' MDF/Sellout Improvement %] [decimal](16, 1) NULL,
 ['+@sow + ' SOW] [varchar](100) NULL,
 ['+@q_prev_year + ' WMGO Ratio] [decimal](16, 1) NULL,
 ['+@q_prev_year + ' MGO] [decimal](16, 1) NULL,
 ['+@q_prev_year + ' (W) MGO] [decimal](16, 1) NULL,
 ['+@q_prev_year + ' (W) MGO ROI] [decimal](16, 1) NULL,
 [Partner ID] [varchar](100) NULL,
 [Geo] [varchar](100) NULL,
 [Country] [varchar](100) NULL,
 [District][varchar](100) NULL,
 [Budget] [varchar](100) NULL,
 [Projected Accuracy] [varchar](100) NULL,
 [Projection Method] [varchar](15) NULL,
 [Assessment] [varchar](100) NULL,
 [Alignment] [varchar](100) NULL,
 [Reasons for Variance] [varchar](200) NULL

)