//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppConfig
    {
        public short ID { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public string Params { get; set; }
        public string ScreenName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
