//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUBudget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUBudget()
        {
            this.ProgramMDFs = new HashSet<ProgramMDF>();
        }
    
        public long BUBudgetID { get; set; }
        public Nullable<short> BusinessUnitID { get; set; }
        public Nullable<decimal> TotalMDF { get; set; }
        public Nullable<decimal> ProgramMDF { get; set; }
        public Nullable<decimal> CountryReserveMDF { get; set; }
        public Nullable<decimal> BaselineMDF { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> VersionID { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramMDF> ProgramMDFs { get; set; }
        public virtual MDFPlanning MDFPlanning { get; set; }
    }
}
