//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContraWeb_Upload_TimeTracker
    {
        public int Id { get; set; }
        public int FileId { get; set; }
        public Nullable<System.DateTime> SSISStartTime { get; set; }
        public Nullable<System.DateTime> SSISEndTime { get; set; }
        public Nullable<System.DateTime> SSISPRODStartTime { get; set; }
        public Nullable<System.DateTime> SSISPRODEndTime { get; set; }
        public Nullable<int> RowCount { get; set; }
    
        public virtual ContraWeb_Upload_DataFile ContraWeb_Upload_DataFile { get; set; }
    }
}
