//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContraWeb_Upload_GeoMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContraWeb_Upload_GeoMapping()
        {
            this.ContraWeb_Upload_CountryMapping = new HashSet<ContraWeb_Upload_CountryMapping>();
        }
    
        public int ID { get; set; }
        public int FileID { get; set; }
        public Nullable<short> GeoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContraWeb_Upload_CountryMapping> ContraWeb_Upload_CountryMapping { get; set; }
        public virtual ContraWeb_Upload_DataFile ContraWeb_Upload_DataFile { get; set; }
        public virtual Geo Geo { get; set; }
    }
}
