//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContraWeb_Upload_DataFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContraWeb_Upload_DataFile()
        {
            this.ContraWeb_Upload_CountryMapping = new HashSet<ContraWeb_Upload_CountryMapping>();
            this.ContraWeb_Upload_GeoMapping = new HashSet<ContraWeb_Upload_GeoMapping>();
            this.ContraWeb_Upload_FinancialYearMapping = new HashSet<ContraWeb_Upload_FinancialYearMapping>();
            this.ContraWeb_Upload_TimeTracker = new HashSet<ContraWeb_Upload_TimeTracker>();
        }
    
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public string FileName { get; set; }
        public string ContainerName { get; set; }
        public string FilePath { get; set; }
        public string DataLevel { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public bool IsDeleted { get; set; }
        public string UploadedBy { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SelectedCriteria { get; set; }
        public string FileNameForBlob { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContraWeb_Upload_CountryMapping> ContraWeb_Upload_CountryMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContraWeb_Upload_GeoMapping> ContraWeb_Upload_GeoMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContraWeb_Upload_FinancialYearMapping> ContraWeb_Upload_FinancialYearMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContraWeb_Upload_TimeTracker> ContraWeb_Upload_TimeTracker { get; set; }
        public virtual ContraWeb_Upload_StatusMaster ContraWeb_Upload_StatusMaster { get; set; }
    }
}
