//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlossaryScreenParameterDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GlossaryScreenParameterDetail()
        {
            this.GlossaryScreenParameterEditDetails = new HashSet<GlossaryScreenParameterEditDetail>();
        }
    
        public int ID { get; set; }
        public int ScreenID { get; set; }
        public string ParameterName { get; set; }
        public string RefinedParameter { get; set; }
        public string Description { get; set; }
        public string RefinedDescription { get; set; }
        public string Icon { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string TableColumn { get; set; }
        public Nullable<bool> IsFilter { get; set; }
        public bool ExtendedView { get; set; }
        public bool Round2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlossaryScreenParameterEditDetail> GlossaryScreenParameterEditDetails { get; set; }
        public virtual GlossaryScreenDetail GlossaryScreenDetail { get; set; }
    }
}
