//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlossaryScreenDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GlossaryScreenDetail()
        {
            this.GlossaryScreenEditDetails = new HashSet<GlossaryScreenEditDetail>();
            this.GlossaryScreenParameterDetails = new HashSet<GlossaryScreenParameterDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string ScreenName { get; set; }
        public string Description { get; set; }
        public string Formula { get; set; }
        public string RefinedFormula { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public bool IsChild { get; set; }
        public Nullable<int> ParentScreenID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlossaryScreenEditDetail> GlossaryScreenEditDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlossaryScreenParameterDetail> GlossaryScreenParameterDetails { get; set; }
    }
}
