//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardRailsConfig
    {
        public int GuardRailConfigID { get; set; }
        public int GuardRailFYConfigID { get; set; }
        public Nullable<decimal> ProgramCarveOutComplaintValue { get; set; }
        public Nullable<decimal> ProgramCarveOutNonComplaintValue { get; set; }
        public Nullable<decimal> ActualMDFAllocationComplaintValue { get; set; }
        public Nullable<decimal> ActualMDFAllocationNonComplaintValue { get; set; }
        public Nullable<decimal> MDFSelloutIndexComplaintValue { get; set; }
        public Nullable<decimal> MDFSelloutIndexNonComplaintValue { get; set; }
        public Nullable<decimal> OverAllocationComplaintValue { get; set; }
        public Nullable<decimal> OverAllocationNonComplaintValue { get; set; }
        public string AllowOverAllocation { get; set; }
        public Nullable<decimal> UnderAllocationComplaintValue { get; set; }
        public Nullable<decimal> UnderAllocationNonComplaintValue { get; set; }
        public Nullable<int> ReviewerRoleID1 { get; set; }
        public Nullable<int> ReviewerRoleID2 { get; set; }
        public Nullable<int> ReviewerRoleID3 { get; set; }
        public Nullable<int> ReviewerRoleID4 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
