//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAuthentication
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string TokenID { get; set; }
        public Nullable<System.DateTime> LogInTime { get; set; }
        public Nullable<System.DateTime> LogOffTime { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
