//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilestoneNotification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MilestoneNotification()
        {
            this.MilestoneNotificationsRoles = new HashSet<MilestoneNotificationsRole>();
        }
    
        public int MilestoneNotificationID { get; set; }
        public int MilestoneFYConfigID { get; set; }
        public Nullable<System.DateTime> MilestoneDate { get; set; }
        public string ReminderEmailMessage1 { get; set; }
        public Nullable<int> SetReminderAlertDays1 { get; set; }
        public Nullable<bool> ReminderStatus1 { get; set; }
        public string ReminderEmailMessage2 { get; set; }
        public Nullable<int> SetReminderAlertDays2 { get; set; }
        public Nullable<bool> ReminderStatus2 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> MilestoneOrderNo { get; set; }
        public string MilestoneName { get; set; }
    
        public virtual MilestoneFYConfig MilestoneFYConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MilestoneNotificationsRole> MilestoneNotificationsRoles { get; set; }
    }
}
