//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelParameterTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelParameterTable()
        {
            this.ModelBUParameterTables = new HashSet<ModelBUParameterTable>();
        }
    
        public int ModelParameterID { get; set; }
        public Nullable<decimal> Max_Sellout_HighDecline_Max_MDF { get; set; }
        public Nullable<decimal> Max_Sellout_HighDecline_Min_MDF { get; set; }
        public Nullable<decimal> Max_Sellout_ModerateDecline_Max_MDF { get; set; }
        public Nullable<decimal> Max_Sellout_ModerateDecline_Min_MDF { get; set; }
        public Nullable<decimal> Max_Sellout_Steady_Max_MDF { get; set; }
        public Nullable<decimal> Max_Sellout_Steady_Min_MDF { get; set; }
        public Nullable<decimal> Max_Sellout_ModerateGrowth_Max_MDF { get; set; }
        public Nullable<decimal> Max_Sellout_ModerateGrowth_Min_MDF { get; set; }
        public Nullable<decimal> Max_Sellout_HighGrowth_Max { get; set; }
        public Nullable<decimal> Max_Sellout_HighGrowth_Min { get; set; }
        public Nullable<decimal> Target_accomplish_HighPrecision_Score { get; set; }
        public Nullable<decimal> Target_accomplish_MediumPrecision_Score { get; set; }
        public Nullable<decimal> Max_Target_Accomplish_percentage { get; set; }
        public Nullable<decimal> Min_Target_Accomplish_percentage { get; set; }
        public Nullable<decimal> JPB_Max { get; set; }
        public Nullable<decimal> JPB_Min { get; set; }
        public Nullable<decimal> Prediction_High_Max { get; set; }
        public Nullable<decimal> Prediction_High_Min { get; set; }
        public Nullable<decimal> Prediction_Low_Max { get; set; }
        public Nullable<decimal> Prediction_Low_Min { get; set; }
        public Nullable<decimal> Weights_applied_t_1H { get; set; }
        public Nullable<decimal> Weights_applied_t_2H { get; set; }
        public Nullable<decimal> Weights_applied_t_3H { get; set; }
        public Nullable<decimal> Min_Target_Productivity { get; set; }
        public Nullable<decimal> Last_Quarter_Sellout_Scale_Factor { get; set; }
        public Nullable<decimal> partner_size_threshold { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> VersionID { get; set; }
        public Nullable<decimal> WMGO_Perf_Acc_High { get; set; }
        public Nullable<decimal> WMGO_Perf_Acc_Low { get; set; }
        public Nullable<decimal> WMGO_Perf_Acc_VeryHigh { get; set; }
        public Nullable<decimal> WMGO_Perf_Acc_VeryLow { get; set; }
        public Nullable<decimal> WMGO_Perf_Acc_Medium { get; set; }
    
        public virtual MDFPlanning MDFPlanning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelBUParameterTable> ModelBUParameterTables { get; set; }
    }
}
