//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelOutputSummaryTable
    {
        public int OutputSummaryID { get; set; }
        public Nullable<int> ModelParameterID { get; set; }
        public string Business_Unit { get; set; }
        public Nullable<decimal> Allocated { get; set; }
        public Nullable<decimal> Remaining { get; set; }
        public Nullable<decimal> Sales_Growth_With_MDF { get; set; }
        public Nullable<decimal> Sales_Growth_Without_MDF { get; set; }
        public Nullable<decimal> MDF_over_Sellout_Last_Period { get; set; }
        public Nullable<decimal> MDF_over_Sellout_Current_Period { get; set; }
        public Nullable<decimal> Aligned { get; set; }
        public Nullable<decimal> MisAligned { get; set; }
        public Nullable<decimal> sustain_percentage { get; set; }
        public Nullable<decimal> growth_percentage { get; set; }
        public Nullable<decimal> MDF_Platinum { get; set; }
        public Nullable<decimal> MDF_Gold { get; set; }
        public Nullable<decimal> MDF_SB { get; set; }
        public Nullable<short> BusinessUnitID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> VersionID { get; set; }
    
        public virtual MDFPlanning MDFPlanning { get; set; }
    }
}
