//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelBUParameterTable
    {
        public int ModelBUParameterID { get; set; }
        public Nullable<int> ModelParameterID { get; set; }
        public Nullable<short> BusinessUnitID { get; set; }
        public Nullable<decimal> High_Performance { get; set; }
        public Nullable<decimal> Min_Partner_Investment { get; set; }
        public Nullable<decimal> New_Partner_RampUp_Scale { get; set; }
        public Nullable<decimal> Preferred_Partner_Cut_Off_Percentage { get; set; }
        public Nullable<decimal> Dist_cust_membership_weight_Silver_and_Below { get; set; }
        public Nullable<decimal> Dist_cust_membership_weight_Platinum_and_Gold { get; set; }
        public Nullable<decimal> Medium_Performance { get; set; }
        public Nullable<decimal> Low_Performance { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> Growth_Revenue { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual ModelParameterTable ModelParameterTable { get; set; }
    }
}
