//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public string PartnerID { get; set; }
        public string PartnerShortName { get; set; }
        public Nullable<int> PartnerTypeID { get; set; }
        public string PartnerName { get; set; }
        public Nullable<int> MembershipTypeID { get; set; }
        public Nullable<short> CountryID { get; set; }
        public string IsActive { get; set; }
        public Nullable<short> DistrictID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual PartnerType PartnerType { get; set; }
    }
}
