//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerSale
    {
        public long PartnerSalesID { get; set; }
        public Nullable<short> GeoID { get; set; }
        public string Geo { get; set; }
        public Nullable<short> CountryID { get; set; }
        public string Country { get; set; }
        public string District { get; set; }
        public string PartnerID { get; set; }
        public string PartnerName { get; set; }
        public Nullable<short> PartnerTypeID { get; set; }
        public string PartnerType { get; set; }
        public Nullable<short> MembershipTypeID { get; set; }
        public string Membership { get; set; }
        public string BG { get; set; }
        public Nullable<short> BusinessUnitID { get; set; }
        public string BusinessUnit { get; set; }
        public Nullable<long> FinancialYearID { get; set; }
        public string FinancialYear { get; set; }
        public Nullable<decimal> Planned_1H { get; set; }
        public Nullable<decimal> Planned_2H { get; set; }
        public Nullable<decimal> Quota_1H { get; set; }
        public Nullable<decimal> Quota_2H { get; set; }
        public Nullable<decimal> SellOut_Amount_Q1 { get; set; }
        public Nullable<decimal> SellOut_Amount_Q2 { get; set; }
        public Nullable<decimal> SellOut_Amount_Q3 { get; set; }
        public Nullable<decimal> SellOut_Amount_Q4 { get; set; }
        public Nullable<decimal> SellOut_Q1 { get; set; }
        public Nullable<decimal> SellOut_Q2 { get; set; }
        public Nullable<decimal> SellOut_Q3 { get; set; }
        public Nullable<decimal> SellOut_Q4 { get; set; }
        public Nullable<decimal> SellOut_1H { get; set; }
        public Nullable<decimal> SellOut_2H { get; set; }
        public Nullable<decimal> SOB_Q1 { get; set; }
        public Nullable<decimal> SOB_Q2 { get; set; }
        public Nullable<decimal> SOB_Q3 { get; set; }
        public Nullable<decimal> SOB_Q4 { get; set; }
        public Nullable<decimal> SOB_1H { get; set; }
        public Nullable<decimal> SOB_2H { get; set; }
        public Nullable<decimal> SellOutNet_Q1 { get; set; }
        public Nullable<decimal> SellOutNet_Q2 { get; set; }
        public Nullable<decimal> SellOutNet_Q3 { get; set; }
        public Nullable<decimal> SellOutNet_Q4 { get; set; }
        public Nullable<decimal> SellOutForPlatinumAndGold_Q1 { get; set; }
        public Nullable<decimal> SellOutForPlatinumAndGold_Q2 { get; set; }
        public Nullable<decimal> SellOutForPlatinumAndGold_Q3 { get; set; }
        public Nullable<decimal> SellOutForPlatinumAndGold_Q4 { get; set; }
        public Nullable<decimal> SellOutForPlatinumAndGold_1H { get; set; }
        public Nullable<decimal> SellOutForPlatinumAndGold_2H { get; set; }
        public Nullable<decimal> SellOutForSilverAndBelow_Q1 { get; set; }
        public Nullable<decimal> SellOutForSilverAndBelow_Q2 { get; set; }
        public Nullable<decimal> SellOutForSilverAndBelow_Q3 { get; set; }
        public Nullable<decimal> SellOutForSilverAndBelow_Q4 { get; set; }
        public Nullable<decimal> SellOutForSilverAndBelow_1H { get; set; }
        public Nullable<decimal> SellOutForSilverAndBelow_2H { get; set; }
        public Nullable<decimal> PBM { get; set; }
        public Nullable<decimal> PMM { get; set; }
        public Nullable<decimal> Ranking { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> DistrictID { get; set; }
        public Nullable<decimal> MDF_1H { get; set; }
        public Nullable<decimal> MDF_2H { get; set; }
        public string Prediction_Method { get; set; }
        public string Prediction_Accuracy { get; set; }
        public Nullable<decimal> Proj_Sales { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> MGO_1H { get; set; }
        public Nullable<decimal> MGO_2H { get; set; }
        public Nullable<decimal> Won_MGO_1H { get; set; }
        public Nullable<decimal> Won_MGO_2H { get; set; }
        public Nullable<decimal> MGO_ROI_1H { get; set; }
        public Nullable<decimal> MGO_ROI_2H { get; set; }
        public Nullable<decimal> Won_MGO_ROI_1H { get; set; }
        public Nullable<decimal> Won_MGO_ROI_2H { get; set; }
        public Nullable<decimal> SOW_Q4 { get; set; }
    
        public virtual District District1 { get; set; }
    }
}
