//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerBudget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerBudget()
        {
            this.PartnerBUBudgets = new HashSet<PartnerBUBudget>();
        }
    
        public long PartnerBudgetID { get; set; }
        public string PartnerID { get; set; }
        public string Membership_Type { get; set; }
        public Nullable<decimal> MSA { get; set; }
        public Nullable<long> ModelParameterID { get; set; }
        public Nullable<short> CountryID { get; set; }
        public Nullable<short> DistrictID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> VersionID { get; set; }
        public Nullable<decimal> Aruba_MSA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerBUBudget> PartnerBUBudgets { get; set; }
        public virtual MDFPlanning MDFPlanning { get; set; }
    }
}
