//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPOWR.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerBUBudget
    {
        public long PartnerBUBudgetID { get; set; }
        public long PartnerBudgetID { get; set; }
        public short BusinessUnitID { get; set; }
        public Nullable<int> MDFVarianceReasonID { get; set; }
        public Nullable<int> FocusedAreaID { get; set; }
        public Nullable<decimal> Baseline_MDF { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> Additional_RecommendedMDF { get; set; }
        public Nullable<decimal> Additional_MDF { get; set; }
        public string Additional_MDF_Reason { get; set; }
        public Nullable<long> BUBudgetID { get; set; }
        public Nullable<long> ModelParamROutputID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> MSA { get; set; }
        public Nullable<decimal> TotalMDF { get; set; }
        public Nullable<decimal> PrevPeriodMDF { get; set; }
        public Nullable<decimal> PrevPrevPeriodMDF { get; set; }
        public Nullable<decimal> CarveOut { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
        public virtual PartnerBudget PartnerBudget { get; set; }
    }
}
